---
title: "Sim_gp_11_26"
author: "Joonwon Lee"
date: "2023-11-27"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, include=FALSE}
library(fields)
library(GpGp)
library(MASS)
library(ggplot2)
```


# True 

```{r, cache=TRUE, results='hide'}

x_min <- 0
y_min <- 0
x_max <- 100
y_max <- 100
# x_max <- floor(n/10)
# y_max <- floor(n/10)

theta = 3
range = 1

n = 500
x <- runif(n, min = x_min, max = x_max)
y <- runif(n, min = y_min, max = y_max)  
d <- sqrt(outer(x,x,"-")^2 + outer(y,y,"-")^2 )
cov_mat = theta * exp(-d/range)
cov_mat2 = theta * exp(- (d/range)^2)
cov_mat3 = theta * (1 + d/range) * exp(-d/range)
ev = eigen(cov_mat)
ev2 = eigen(cov_mat2)
ev3 = eigen(cov_mat3)

nn = c(500,1000,2000)
sim_data <- rmvnorm(n=nn[1], mean = rep(0, length(n)), sigma= cov_mat3)
# sum(var(sim_data2)- cov_mat)

tmp1 = rep(0,nn[1])
tmp2 = rep(0,nn[1])
tmp3 = rep(0,nn[1])

tmp1 = sim_data %*% (ev$vectors[,n]) *ev$values[n]^{-1/2}  
tmp2 = sim_data %*% (ev2$vectors[,n]) *ev2$values[n]^{-1/2} 
tmp3 = sim_data %*% (ev3$vectors[,n]) *ev3$values[n]^{-1/2}


par(mfrow=c(1,3))
plot((1:nn[1]),tmp1, ylim =c(-10,10))
abline(h=0, col="red")

plot((1:nn[1]),tmp2, ylim=c(-10,10))
abline(h=0, col="red")
plot((1:nn[1]),tmp3, ylim= c(-10,10))
abline(h=0, col="red")

tmp1 = rep(0,n)
tmp2 = rep(0,n)
tmp3 = rep(0,n)

for (i in 1:n){
  tmp1[i] = t(ev$vectors[,i]) %*%(sim_data) / ev$values[i]^{1/2} 
  tmp2[i] = t(ev2$vectors[,i]) %*%(rnorm(n,sd=5)) / ev2$values[i]^{1/2}
  tmp3[i] = t(ev3$vectors[,i]) %*%(sim_data) / ev3$values[i]^{1/2}
}

par(mfrow=c(1,3))
plot((1:n),tmp1, ylim= c(0,10) )
plot((1:n),tmp2, ylim=c(0,10))
plot((1:n),tmp3, ylim= c(0,10))

```

# This is for figure 1 and figure 2 in latex file "Diagnostics using eigenvalues".

```{r, cache=TRUE, results='hide'}
x_min <- 0
y_min <- 0
x_max <- 100
y_max <- 100
# x_max <- floor(n/10)
# y_max <- floor(n/10)

theta = 3
range = 1

n = 1000
x <- runif(n, min = x_min, max = x_max)
y <- runif(n, min = y_min, max = y_max)  
d <- sqrt(outer(x,x,"-")^2 + outer(y,y,"-")^2 )
cov_mat = theta * exp(-d/range)
cov_mat2 = theta * exp(- (d/range)^2)
cov_mat3 = theta * (1 + d/range) * exp(-d/range)
ev = eigen(cov_mat)
ev2 = eigen(cov_mat2)
ev3 = eigen(cov_mat3)

chol_matrix = chol(cov_mat)
z_list <- rnorm(n)
sim_data <- t(chol_matrix) %*% z_list

nn = c(500,1000,2000)
sim_data <- rmvnorm(n=nn[1], mean = rep(0, length(n)), sigma= cov_mat)
# sum(var(sim_data2)- cov_mat)

tmp1 = rep(0,n)
tmp2 = rep(0,n)
tmp3 = rep(0,n)
for (i in 1:n){
  tmp1[i] = t(ev$vectors[,i]) %*% var(sim_data) %*% ev$vectors[,i]* ev$values[i]^{-1}  
  tmp2[i] = t(ev2$vectors[,i]) %*% var(sim_data) %*% ev2$vectors[,i]* ev2$values[i]^{-1} 
  tmp3[i] = t(ev3$vectors[,i]) %*% var(sim_data) %*% ev3$vectors[,i]* ev3$values[i]^{-1}
}

par(mfrow=c(1,3))
plot((1:n),tmp1, xlab="eigen_val", ylab="model: exp ", ylim= c(0,10))
abline(h=1, col="red")
plot((1:n),tmp2, xlab="eigen_val", ylab="model: exp sq", ylim=c(0,10))
abline(h=1, col="red")
plot((1:n),tmp3, xlab="eigen_val",  ylab="model: matern", ylim= c(0,10))
abline(h=1, col="red")

```


